### ISSUE TITLE
Distractions in between the play

### ISSUE THREAD

**Issue by gsthina** [GSThina/space-invader#19]
Add more distractions to the game, making it more challenging.

**Comment by lavanyaParamashivam** [comment]
Can have invaders in right nd left side of your mobile display up to half screen of mobile not more than that.

**Comment by gsthina** [comment]
Hi @lavanyaParamashivam , you do you mean to say that the aliens can come until the half of the screen (y-axis) and should cause damage to us?

**Comment by lavanyaParamashivam** [comment]
Hi Thina
Yup,exactly! But horizontal.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: G Surendar Thina <notifications@github.com> Date: 2/27/19  16:39  (GMT+05:30) To: GSThina/space-invader <space-invader@noreply.github.com> Cc: lavanyaParamashivam <sailavi22@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [GSThina/space-invader] Distractions in between the play (#19) 
Hi @lavanyaParamashivam , you do you mean to say that the aliens can come until the half of the screen (y-axis) and should cause damage to us?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GSThina/space-invader","title":"GSThina/space-invader","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/GSThina/space-invader"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GSThina in #19: Hi @lavanyaParamashivam , you do you mean to say that the aliens can come until the half of the screen (y-axis) and should cause damage to us?"}],"action":{"name":"View Issue","url":"https://github.com/GSThina/space-invader/issues/19#issuecomment-467821603"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/GSThina/space-invader/issues/19#issuecomment-467821603",
"url": "https://github.com/GSThina/space-invader/issues/19#issuecomment-467821603",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gsthina** [comment]
Yes, currently workin' on this!

**Comment by gsthina** [comment]
Adding a new issue based up on your comment @lavanyaParamashivam :)

**Comment by gsthina** [comment]
Any object other than aliens is considered as distractions. Hitting them will reduce health.

**Comment by gsthina** [comment]
Added different health portions for improving health, which will come in random.
